# Copyright (c) 2022 - 2022, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

# The main target of the analysis
target: include('analyze_target', required=True)

# The list of direct dependencies
dependencies: list(include('analyze_target'), min=0, required=False)

---
analyze_target:
  id: str(required=True)

  # The url of the remote repository or a local path
  path: str(required=True)

  # Optional, if not specified we use the default branch
  branch: str(required=False)

  # Optional, if not specified we use the latest commit
  digest: str(required=False)
