# Copyright (c) 2023 - 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

# This workflow deploys the documentations to GitHub Pages.
name: Deploy static content to Pages
on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        required: true
        description: The artifact name that contains docs content
      artifact-sha256:
        type: string
        required: true
        description: The sha of the artifact that contains docs content
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Download the generated docs archive, verify its hash, and deploy to GitHub pages.
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        fetch-depth: 0

    - name: Download artifact
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        name: ${{ inputs.artifact-name }}
        path: dist

    # Verify hashes by first computing hashes for the artifacts and then comparing them
    # against the hashes for the artifact.
    - name: Verify the artifact hash
      env:
        ARTIFACT_HASH: ${{ inputs.artifact-sha256 }}
      run: |
        set -euo pipefail
        echo "Hash of package should be $ARTIFACT_HASH."
        echo "$ARTIFACT_HASH" | base64 --decode | sha256sum --strict --check --status || exit 1

    # Prepare the docs content.
    - name: Prepare docs for release
      env:
        DIST_PATH: dist
      run: |
        DOCS_PATH=$(find "$DIST_PATH" -depth -type f -name 'macaron-*-docs-html.zip' | head -n 1)
        if [[ -z "${DOCS_PATH}" ]];
        then
            echo "Unable to find Macaron docs files in ${DIST_PATH}."
            exit 1
        fi
        unzip "$DOCS_PATH"

    - name: Setup Pages
      uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # v3.0.6

    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@66b63f4a7de003f4f00cc8e9af4b83b8f2abdb96 # v1.0.9
      with:
        # Upload html/ directory.
        path: html

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@9dbe3824824f8a1377b8e298bafde1a50ede43e5 # v2.0.4
