# Copyright (c) 2023 - 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

# This workflow builds the base Macaron Docker image. The base image will be pushed to ghcr.io.
# This base image contains the necessary components to build and run Macaron as a Docker image.

name: Build Macaron base image
on:
  workflow_dispatch:
  push:
    branches:
    - add-docker-images

permissions:
  contents: read
  packages: write

jobs:
  build-macaron-base:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      with:
        fetch-depth: 0

    # The log in step is necessary to push the image to ghcr.io.
    - name: Log in to GitHub Container Registry
      run: docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    # Build and push the Macaron base image using docker/Dockerfile.base. Note that this build
    # only requires docker/Dockerfile.base. The base image will be tagged with ghcr.io/oracle-samples/macaron-base:latest.
    - name: Build and push Macaron base image
      run: |
        docker build -t ghcr.io/oracle-samples/macaron-base:latest -f docker/Dockerfile.base docker/
        docker push ghcr.io/oracle-samples/macaron-base:latest
